# Generated by Django 5.0.14 on 2026-07-19 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Estoque',
                'verbose_name_plural': 'Categorias de Estoque',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['active'], name='stock_stock_active_a7c0fd_idx'), models.Index(fields=['sort_order'], name='stock_stock_sort_or_73d630_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_checks', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Conferência de Estoque',
                'verbose_name_plural': 'Conferências de Estoque',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.stockcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Item (snapshot)')),
                ('status', models.CharField(choices=[('LOW', 'Estoque baixo'), ('OUT', 'Acabou')], max_length=3, verbose_name='Status')),
                ('stock_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.stockcheck', verbose_name='Conferência')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_items', to='stock.stockitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item da Conferência',
                'verbose_name_plural': 'Itens da Conferência',
                'ordering': ['stock_check', 'item_name'],
            },
        ),
        migrations.AddIndex(
            model_name='stockcheck',
            index=models.Index(fields=['-date'], name='stock_stock_date_6eddb8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['category'], name='stock_stock_categor_b22d77_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['active'], name='stock_stock_active_a8be49_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['sort_order'], name='stock_stock_sort_or_d7367a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_stock_item_per_category'),
        ),
        migrations.AddIndex(
            model_name='stockcheckitem',
            index=models.Index(fields=['stock_check'], name='stock_stock_stock_c_e53ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcheckitem',
            index=models.Index(fields=['status'], name='stock_stock_status_6d87be_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcheckitem',
            constraint=models.UniqueConstraint(fields=('stock_check', 'item'), name='unique_item_per_check'),
        ),
    ]
