# Generated by Django 5.0.14 on 2026-07-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcheckitem',
            name='buy_quantity',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Quantidade a comprar'),
        ),
    ]
