services:
  # Web Service
  - type: web
    name: gestao-financeira
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: "./build.sh"
    startCommand: "gunicorn gestao_financeira.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        sync: false
      - key: RENDER
        value: true
