# Generated by Django 5.0.14 on 2026-06-20 23:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data do fechamento (única por dia)', unique=True, verbose_name='Data')),
                ('order_count', models.PositiveIntegerField(help_text='Total de pedidos realizados no dia', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Pedidos')),
                ('cash_sales', models.DecimalField(decimal_places=2, help_text='Total de vendas pagas em dinheiro', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Vendas em Dinheiro')),
                ('pix_sales', models.DecimalField(decimal_places=2, help_text='Total de vendas pagas via Pix', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Vendas em Pix')),
                ('card_sales', models.DecimalField(decimal_places=2, help_text='Total de vendas pagas com cartão', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Vendas em Cartão')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre o dia (opcional)', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fechamento Diário',
                'verbose_name_plural': 'Fechamentos Diários',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='finance_dai_date_e07a68_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=100, unique=True, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, help_text='Categoria ativa para uso', verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Despesa',
                'verbose_name_plural': 'Categorias de Despesas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='finance_exp_name_11f00e_idx'), models.Index(fields=['active'], name='finance_exp_active_f1fb2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data da despesa', verbose_name='Data')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da despesa em reais', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da despesa (opcional)', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(help_text='Categoria da despesa', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='finance_exp_date_cee3da_idx'), models.Index(fields=['category'], name='finance_exp_categor_e43046_idx'), models.Index(fields=['-date', 'category'], name='finance_exp_date_5dcb2d_idx')],
            },
        ),
    ]
