# Generated by Django 5.0.14 on 2026-06-20 23:35

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """
    Cria as categorias iniciais de despesas.
    """
    ExpenseCategory = apps.get_model('finance', 'ExpenseCategory')

    categories = [
        'Ingredientes',
        'Embalagens',
        'Entrega',
        'Combustível',
        'Energia',
        'Internet',
        'Marketing',
        'Equipamentos',
        'Manutenção',
        'Outros',
    ]

    for category_name in categories:
        ExpenseCategory.objects.get_or_create(
            name=category_name,
            defaults={'active': True}
        )


def remove_initial_categories(apps, schema_editor):
    """
    Remove as categorias iniciais (reverso da migration).
    """
    ExpenseCategory = apps.get_model('finance', 'ExpenseCategory')

    categories = [
        'Ingredientes',
        'Embalagens',
        'Entrega',
        'Combustível',
        'Energia',
        'Internet',
        'Marketing',
        'Equipamentos',
        'Manutenção',
        'Outros',
    ]

    ExpenseCategory.objects.filter(name__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_categories,
            reverse_code=remove_initial_categories
        ),
    ]
