# Generated by Django 5.0.14 on 2026-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_create_initial_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ORDERS', 'Pedidos')], default='MANUAL', help_text='MANUAL: preenchido manualmente; ORDERS: calculado a partir dos pedidos', max_length=10, verbose_name='Fonte'),
        ),
    ]
