# Generated by Django 5.0.14 on 2026-07-15 17:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço (R$)')),
                ('is_free_option', models.BooleanField(default=False, help_text='Pode ser selecionado como adicional incluído no limite do Monte seu Açaí', verbose_name='Elegível como grátis')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['active'], name='orders_addo_active_fa1f9c_idx'), models.Index(fields=['is_free_option'], name='orders_addo_is_free_3e524a_idx'), models.Index(fields=['sort_order'], name='orders_addo_sort_or_f6c041_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('kind', models.CharField(choices=[('STANDARD', 'Padrão'), ('BUILD_YOUR_OWN', 'Monte seu Açaí'), ('ADDON', 'Adicional'), ('OTHER', 'Outro')], help_text='Direciona o comportamento na tela de lançamento', max_length=20, verbose_name='Tipo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['active'], name='orders_prod_active_ca191f_idx'), models.Index(fields=['sort_order'], name='orders_prod_sort_or_3f3235_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Composição do produto', verbose_name='Descrição')),
                ('product_type', models.CharField(choices=[('STANDARD', 'Padrão'), ('BUILD_YOUR_OWN', 'Monte seu Açaí'), ('ADDON', 'Adicional')], max_length=20, verbose_name='Tipo de produto')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='orders.productcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 300 ml, 2 litros', max_length=50, verbose_name='Nome')),
                ('volume_ml', models.PositiveIntegerField(help_text='Volume em mililitros — usado em relatórios de litros vendidos', verbose_name='Volume (ml)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['sort_order', 'volume_ml'],
                'indexes': [models.Index(fields=['active'], name='orders_size_active_85303e_idx'), models.Index(fields=['sort_order'], name='orders_size_sort_or_62c2c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço (R$)')),
                ('included_addons_limit', models.PositiveIntegerField(default=0, help_text='Adicionais gratuitos permitidos (apenas Monte seu Açaí)', verbose_name='Limite de adicionais incluídos')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='orders.product', verbose_name='Produto')),
                ('size', models.ForeignKey(blank=True, help_text='Deixe em branco para produtos sem tamanho', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='orders.size', verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produtos',
                'ordering': ['product', 'size__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='orders_prod_categor_56d6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='orders_prod_active_35e5df_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='orders_prod_product_a01da2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sort_order'], name='orders_prod_sort_or_32c718_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='orders_prod_product_9f1f90_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['active'], name='orders_prod_active_78bb9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('size__isnull', False)), fields=('product', 'size'), name='unique_product_size_non_null'),
        ),
    ]
