# Generated by Django 5.0.14 on 2026-07-15 17:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comanda_number', models.CharField(help_text='Referência do papel físico — não é único', max_length=20, verbose_name='Número da comanda')),
                ('order_date', models.DateField(verbose_name='Data')),
                ('order_time', models.TimeField(help_text='Horário da comanda (HH:MM)', verbose_name='Horário')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('CASH', 'Dinheiro'), ('CARD', 'Cartão')], max_length=10, verbose_name='Forma de pagamento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total (calculado)')),
                ('informed_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor escrito na comanda física (opcional)', max_digits=10, null=True, verbose_name='Total informado na comanda')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-order_date', 'order_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('product_name', models.CharField(max_length=200, verbose_name='Produto (snapshot)')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='Variação (snapshot)')),
                ('size_name', models.CharField(blank=True, max_length=50, verbose_name='Tamanho (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário (snapshot)')),
                ('addons_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total de adicionais pagos')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total do item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.product', verbose_name='Produto')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.productvariant', verbose_name='Variação')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adicional (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço unitário (snapshot)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('is_included', models.BooleanField(help_text='True = dentro do limite gratuito; False = adicional pago', verbose_name='Incluído no limite')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('addon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_addons', to='orders.addon', verbose_name='Adicional')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.orderitem', verbose_name='Item do pedido')),
            ],
            options={
                'verbose_name': 'Adicional do Item',
                'verbose_name_plural': 'Adicionais do Item',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_orde_order_d_d71205_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date', 'payment_method'], name='orders_orde_order_d_15b2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date', 'order_time'], name='orders_orde_order_d_267ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by'], name='orders_orde_created_780f95_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date', 'comanda_number'], name='orders_orde_order_d_fd0c12_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemaddon',
            index=models.Index(fields=['addon'], name='orders_orde_addon_i_23b5cb_idx'),
        ),
    ]
