# Generated by Django 5.0.14 on 2026-07-15 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_create_operacao_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(choices=[('CATALOG', 'Catálogo'), ('MANUAL', 'Avulso')], default='CATALOG', help_text='CATALOG: produto do catálogo; MANUAL: item avulso sem catálogo', max_length=10, verbose_name='Tipo de item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.productvariant', verbose_name='Variação'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['item_type'], name='orders_orde_item_ty_2b8518_idx'),
        ),
    ]
