# Generated by Django 5.0.14 on 2026-07-21 21:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_order_payments(apps, schema_editor):
    """Cria uma linha de pagamento para cada pedido existente (amount == total)."""
    Order = apps.get_model("orders", "Order")
    OrderPayment = apps.get_model("orders", "OrderPayment")
    payments = [
        OrderPayment(order_id=order.id, method=order.payment_method, amount=order.total)
        for order in Order.objects.all().iterator()
    ]
    OrderPayment.objects.bulk_create(payments, batch_size=500)


def remove_order_payments(apps, schema_editor):
    OrderPayment = apps.get_model("orders", "OrderPayment")
    OrderPayment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_split',
            field=models.BooleanField(default=False, help_text='True quando o pedido foi pago em mais de uma forma (ver linhas de pagamento).', verbose_name='Pagamento dividido'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PIX', 'Pix'), ('CASH', 'Dinheiro'), ('CARD', 'Cartão')], max_length=10, verbose_name='Forma de pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pagamento do Pedido',
                'verbose_name_plural': 'Pagamentos do Pedido',
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_bc1172_idx'), models.Index(fields=['method'], name='orders_orde_method_bf65db_idx')],
            },
        ),
        migrations.RunPython(backfill_order_payments, remove_order_payments),
    ]
